theme: jekyll-theme-minimal
title: [Conta PrÃ³pria]
description: [Para entender tudo sobre dados, desde o mais bÃ¡sico atÃ© inteligÃªncia artificial, e como colocar tudo isso em prÃ¡tica
ğŸ¥ quartas-feiras 18h]
logo: [ce8b2f2a-4e83-4ddf-9fab-443fb47962b2.jpg]
