title: "Conta Propria"
description: "Para entender tudo sobre dados, desde o mais bÃ¡sico atÃ© inteligÃªncia artificial, e como colocar tudo isso em prÃ¡tica|
ğŸ¥ quartas-feiras aaa10 18h"
Logo: (/assets/logo.png)
theme: minimal
