title: "Conta Propria"
description: "Para entender tudo sobre dados, desde o mais bÃ¡sico atÃ© inteligÃªncia artificial, e como colocar tudo isso em prÃ¡tica|
ğŸ¥ quartas-feiras aaa11 18h"
logo: /assets/logo.png
show_downloads: true

theme: jekyll-theme-minimal
