theme: jekyll-theme-minimal
title: "Conta Propria"
description: "Para entender tudo sobre dados, desde o mais bÃ¡sico atÃ© inteligÃªncia artificial, e como colocar tudo isso em prÃ¡tica|
ğŸ¥ quartas-feiras aaa5 18h"
Logo: /ce8b2f2a-4e83-4ddf-9fab-443fb47962b2.jpg
